### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by wongjiahau** [DanielRamosAcosta/swc-jest#5]
I'm getting this error when I try to use this module, some of the test files contain import statements like the following:
```ts
import { runTestCases } from '../src/tests/api-test-helper'
```

**Comment by charliematters** [comment]
I'm also experiencing this problem. Importing the module under test from the jest .spec file fails. My swcrc file looks like this
```
{
    "jsc": {
        "externalHelpers": false,
        "parser": {
            "syntax": "typescript",
            "tsx": true,
            "decorators": true
        }
    }
}
```

And the error looks like:
```
C:\dev\swc\src\DomainObject.spec.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import DomainObject from "./DomainObject";
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1266:14)
```

**Comment by DanielRamosAcosta** [comment]
I'll try to check it out this evening 😄

**Comment by DanielRamosAcosta** [comment]
Could you please provide me a repo that replicates the problem, @charliematters @wongjiahau?

**Comment by charliematters** [comment]
I've put together a simple one here: https://github.com/charliematters/swc-issue

It's actually related to me not being able to get my domain objects working with mobx (another swc issue/question I guess), but running `yarn && yarn test` should show the import problem

**Comment by DanielRamosAcosta** [comment]
Thanks @charliematters, that helps a lot 👍

**Comment by DanielRamosAcosta** [comment]
@charliematters, I've fixed your repo by changeing your `.swcrc`:

```
{
    "jsc": {
        "externalHelpers": false,
        "parser": {
            "syntax": "typescript",
            "tsx": true,
            "decorators": true
        }
    },
    "module": {
        "type": "commonjs"
    }
}
```

By telling Swc to transpile to Commonjs. Remember to clear Jest's cache when you change your config with `jest --clearCache`, please ping me if it works for you

**Comment by charliematters** [comment]
That solves it for me too - thanks!

Now I need to see how I can get decorators working and it will be a straight swap for TSC!

**Comment by DanielRamosAcosta** [comment]
Nice! Tell me if you have any other problems 😄
